// window.__CATALOG__ = [
//   {
//     "id": 101,
//     "productId": "",
//     "priceId": null,
//     "no": "047",
//     "cat": "spirits",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-vintage",
//     "image": "https://maisonhan-images.oss-cn-guangzhou.aliyuncs.com/products/feitianmaotai.jpg",
//     "name": "<em>Moutai</em> Feitian &middot; 1988",
//     "sub": "Single-bottle reserve. One of seventeen in private hands.",
//     "price": 24800,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "Guizhou, China",
//     "year": "1988",
//     "badge": "Vintage Reserve",
//     "desc": "A pre-merger bottling from the original Maotai distillery, sealed under cellophane the week of the Seoul Olympics.",
//     "sortOrder": 10
//   },
//   {
//     "id": 102,
//     "productId": "",
//     "priceId": null,
//     "no": "062",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-japan",
//     "bottle": "hibiki-21",
//     "image": "images/hibiki-21.webp",
//     "name": "<em>Hibiki</em> 21 Year Old",
//     "sub": "Mizunara, sherry and American oak vatting.",
//     "price": 3400,
//     "abv": "43%",
//     "vol": "700 ml",
//     "origin": "Japan",
//     "year": "",
//     "badge": "",
//     "desc": "The crown of Suntory's blending art. Stone fruit, sandalwood, and a ribbon of smoke when the glass is half empty.",
//     "sortOrder": 20
//   },
//   {
//     "id": 103,
//     "productId": "",
//     "priceId": null,
//     "no": "101",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-flying",
//     "image": "images/moutai-ribbon-official.png",
//     "name": "<em>Moutai</em> Feitian &middot; Current Release",
//     "sub": "Ribbon edition presentation referenced on site imagery.",
//     "price": 4200,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "Guizhou, China",
//     "year": "",
//     "badge": "",
//     "desc": "Maps to the flying-Moutai bottle treatment on the static site editorial grid.",
//     "sortOrder": 30
//   },
//   {
//     "id": 104,
//     "productId": "",
//     "priceId": null,
//     "no": "090",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "wuliangye",
//     "image": "images/wuliangye.png",
//     "name": "<em>Wuliangye</em> 1990",
//     "sub": "Strong-aroma baijiu &middot; 52&deg;",
//     "price": 2800,
//     "abv": "52%",
//     "vol": "500 ml",
//     "origin": "Yibin, China",
//     "year": "1990",
//     "badge": "",
//     "desc": "Classic strong-aroma profile from Yibin; complement to the Maison Han Moutai chapter.",
//     "sortOrder": 40
//   },
//   {
//     "id": 105,
//     "productId": "",
//     "priceId": null,
//     "no": "018",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-japan",
//     "bottle": "yamazaki-18",
//     "image": "images/yamazaki-18.png",
//     "name": "<em>Yamazaki</em> 18 Year Old",
//     "sub": "Sherry-forward malt from Japan.",
//     "price": 12000,
//     "abv": "43%",
//     "vol": "700 ml",
//     "origin": "Japan",
//     "year": "",
//     "badge": "",
//     "desc": "Deep sherried Yamazaki in the lineage that defined Japanese single malt globally.",
//     "sortOrder": 50
//   },
//   {
//     "id": 106,
//     "productId": "",
//     "priceId": null,
//     "no": "012",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-japan",
//     "bottle": "hakushu-12",
//     "image": "images/hakushu-12.webp",
//     "name": "<em>Hakushu</em> 12 Year Old",
//     "sub": "Forest distillery profile.",
//     "price": 185,
//     "abv": "43%",
//     "vol": "700 ml",
//     "origin": "Japan",
//     "year": "",
//     "badge": "",
//     "desc": "Highland Hakushu at its approachable middle age ?? greenery, orchard mist, restrained peat.",
//     "sortOrder": 60
//   },
//   {
//     "id": 107,
//     "productId": "",
//     "priceId": null,
//     "no": "NV1",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-japan",
//     "bottle": "yoichi",
//     "image": "images/yoichi.jpg",
//     "name": "<em>Yoichi</em> Single Malt",
//     "sub": "Single-cask coastal Nikka weight.",
//     "price": 450,
//     "abv": "45%",
//     "vol": "700 ml",
//     "origin": "Hokkaido, Japan",
//     "year": "N.V.",
//     "badge": "",
//     "desc": "Coastal peat and restrained fruit from Nikka's Hokkaido cradle.",
//     "sortOrder": 70
//   },
//   {
//     "id": 108,
//     "productId": "",
//     "priceId": null,
//     "no": "084",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-japan",
//     "bottle": "karuizawa",
//     "image": "images/karuizawa.jpg",
//     "name": "<em>Karuizawa</em> 1984 Single Cask",
//     "sub": "Closed distillery legend.",
//     "price": 45000,
//     "abv": "57%",
//     "vol": "700 ml",
//     "origin": "Japan",
//     "year": "1984",
//     "badge": "Closed Distillery",
//     "desc": "From Japan's mythical closed distillery; each cask charts its own obsessive following.",
//     "sortOrder": 80
//   },
//   {
//     "id": 109,
//     "productId": "",
//     "priceId": null,
//     "no": "025",
//     "cat": "whisky",
//     "catLabel": "Whisky",
//     "bv": "bv-scotch",
//     "bottle": "macallan",
//     "image": "images/macallan.jpg",
//     "name": "<em>The Macallan</em> 25 Sherry Oak",
//     "sub": "Speyside sherry-seasoned oak.",
//     "price": 18000,
//     "abv": "43%",
//     "vol": "700 ml",
//     "origin": "Scotland",
//     "year": "25",
//     "badge": "",
//     "desc": "The distillery's reference sherry-matured architecture ?? raisins, saddle leather, old furniture polish.",
//     "sortOrder": 90
//   },
//   {
//     "id": 110,
//     "productId": "",
//     "priceId": null,
//     "no": "082",
//     "cat": "wine",
//     "catLabel": "Wine",
//     "bv": "bv-wine",
//     "bottle": "lafite",
//     "image": "images/lafite.jpg",
//     "name": "Ch&acirc;teau <em>Lafite</em> Rothschild 1982",
//     "sub": "Pauillac first growth.",
//     "price": 8500,
//     "abv": "12.5%",
//     "vol": "750 ml",
//     "origin": "Pauillac, France",
//     "year": "1982",
//     "badge": "",
//     "desc": "A benchmark Pauillac vintage; classic cassis and graphite unfolding over hours in the glass.",
//     "sortOrder": 100
//   },
//   {
//     "id": 111,
//     "productId": "",
//     "priceId": null,
//     "no": "HP1",
//     "cat": "spirits",
//     "catLabel": "Spirits",
//     "bv": "bv-cognac",
//     "bottle": "hennessy",
//     "image": "images/hennessy.jpg",
//     "name": "<em>Hennessy</em> Paradis",
//     "sub": "Extra cognac tier.",
//     "price": 3200,
//     "abv": "40%",
//     "vol": "700 ml",
//     "origin": "Cognac, France",
//     "year": "",
//     "badge": "",
//     "desc": "Blended prestige tier from the House of Hennessy ?? silk, orchard honey, truffle shadow.",
//     "sortOrder": 110
//   },
//   {
//     "id": 114,
//     "productId": "",
//     "priceId": null,
//     "no": "MTFT-02",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-flying",
//     "image": "images/feitianmaotai.jpg",
//     "name": "贵州茅台酒（飞天）",
//     "sub": "茅台核心大单品，酱香标杆，适合礼赠、收藏与高端宴请",
//     "price": 2750,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国贵州",
//     "year": "",
//     "badge": "",
//     "desc": "茅台核心大单品，酱香标杆，适合礼赠、收藏与高端宴请",
//     "sortOrder": 1
//   },
//   {
//     "id": 115,
//     "productId": "",
//     "priceId": null,
//     "no": "MTWX-03",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-flying",
//     "image": "images/wuxingmaotai.jpg",
//     "name": "贵州茅台酒（五星）",
//     "sub": "与飞天同酒质，是茅台的经典款，适合收藏与宴请",
//     "price": 2700,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国贵州",
//     "year": "",
//     "badge": "",
//     "desc": "与飞天同酒质，是茅台的经典款，适合收藏与宴请",
//     "sortOrder": 2
//   },
//   {
//     "id": 116,
//     "productId": "",
//     "priceId": null,
//     "no": "MTWZ-01",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-flying",
//     "image": "images/wangzijiu.jpg",
//     "name": "茅台王子酒（酱色）",
//     "sub": "茅台入门级酱香酒，性价比高，适合日常饮用与入门品鉴",
//     "price": 268,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国贵州",
//     "year": "",
//     "badge": "",
//     "desc": "茅台入门级酱香酒，性价比高，适合日常饮用与入门品鉴",
//     "sortOrder": 3
//   },
//   {
//     "id": 117,
//     "productId": "",
//     "priceId": null,
//     "no": "MTYB-07",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "maotai-flying",
//     "image": "images/maotaiyingbin.jpg",
//     "name": "茅台迎宾酒（紫迎宾）",
//     "sub": "茅台入门级酱香酒，性价比高，适合日常饮用",
//     "price": 128,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国贵州",
//     "year": "",
//     "badge": "",
//     "desc": "茅台入门级酱香酒，性价比高，适合日常饮用",
//     "sortOrder": 4
//   },
//   {
//     "id": 118,
//     "productId": "",
//     "priceId": null,
//     "no": "WLY1618-06",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "wuliangye",
//     "image": "images/wuliangye.jpg",
//     "name": "五粮液（1618）",
//     "sub": "五粮液高端款，口感偏绵柔，适合商务宴请与收藏",
//     "price": 1199,
//     "abv": "52%",
//     "vol": "500 ml",
//     "origin": "中国四川宜宾",
//     "year": "",
//     "badge": "",
//     "desc": "五粮液高端款，口感偏绵柔，适合商务宴请与收藏",
//     "sortOrder": 5
//   },
//   {
//     "id": 119,
//     "productId": "",
//     "priceId": null,
//     "no": "WLY-05",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "wuliangye",
//     "image": "images/wuliangyepuwu.jpg",
//     "name": "五粮液（普五 第八代）",
//     "sub": "浓香型白酒标杆，口感绵柔醇厚，适合宴请与礼赠",
//     "price": 1099,
//     "abv": "52%",
//     "vol": "500 ml",
//     "origin": "中国四川宜宾",
//     "year": "",
//     "badge": "",
//     "desc": "浓香型白酒标杆，口感绵柔醇厚，适合宴请与礼赠",
//     "sortOrder": 6
//   },
//   {
//     "id": 120,
//     "productId": "",
//     "priceId": null,
//     "no": "QHL-09",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "qinghualang",
//     "image": "images/qinghualang.jpg",
//     "name": "青花郎",
//     "sub": "郎酒高端酱香酒，与茅台同属酱香第二梯队，适合收藏与高端宴请",
//     "price": 998,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国四川古蔺",
//     "year": "",
//     "badge": "",
//     "desc": "郎酒高端酱香酒，与茅台同属酱香第二梯队，适合收藏与高端宴请",
//     "sortOrder": 7
//   },
//   {
//     "id": 121,
//     "productId": "",
//     "priceId": null,
//     "no": "HHL15-08",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "honghualang",
//     "image": "images/honghualang.jpg",
//     "name": "红花郎 15",
//     "sub": "郎酒中端酱香酒，红花郎系列经典款，适合礼赠与宴席",
//     "price": 598,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国四川古蔺",
//     "year": "",
//     "badge": "",
//     "desc": "郎酒中端酱香酒，红花郎系列经典款，适合礼赠与宴席",
//     "sortOrder": 8
//   },
//   {
//     "id": 122,
//     "productId": "",
//     "priceId": null,
//     "no": "LM-04",
//     "cat": "baijiu",
//     "catLabel": "Chinese baijiu",
//     "bv": "bv-maotai",
//     "bottle": "laimao",
//     "image": "images/laimao.jpg",
//     "name": "赖茅（端曲）",
//     "sub": "茅台旗下赖茅系列，入门级酱香酒，适合日常饮用",
//     "price": 198,
//     "abv": "53%",
//     "vol": "500 ml",
//     "origin": "中国贵州",
//     "year": "",
//     "badge": "",
//     "desc": "茅台旗下赖茅系列，入门级酱香酒，适合日常饮用",
//     "sortOrder": 9
//   },
//   {
//     "id": 112,
//     "productId": "",
//     "priceId": null,
//     "no": "NK1",
//     "cat": "others",
//     "catLabel": "Others",
//     "bv": "bv-japan",
//     "bottle": "taketsuru",
//     "image": "images/taketsuru.jpg",
//     "name": "<em>Taketsuru</em> Pure Malt",
//     "sub": "Nikka blended malt flagship.",
//     "price": 85,
//     "abv": "43%",
//     "vol": "700 ml",
//     "origin": "Japan",
//     "year": "",
//     "badge": "",
//     "desc": "Nikka's accessible monument to blended malt craft ?? orchard fruit, supple oak, restrained smoke.",
//     "sortOrder": 120
//   },
//   {
//     "id": 113,
//     "productId": "",
//     "priceId": null,
//     "no": "SP1",
//     "cat": "sparkling",
//     "catLabel": "Sparkling",
//     "bv": "bv-wine",
//     "bottle": "sparkling",
//     "image": "images/lafite.jpg",
//     "name": "<em>Champagne</em> Brut Reserve",
//     "sub": "Classic celebratory sparkling.",
//     "price": 260,
//     "abv": "12%",
//     "vol": "750 ml",
//     "origin": "Champagne, France",
//     "year": "N.V.",
//     "badge": "",
//     "desc": "A bright, dry sparkling wine with fine mousse, citrus lift, and a clean mineral finish.",
//     "sortOrder": 115
//   }
// ];
// 已禁用静态数据，改为从后端 API 实时加载
window.__CATALOG__ = [];